//
// IPadFactsView.m
// Generated by Core Animator version 1.1.1 on 7/15/15.
//
// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED AND WILL BE OVERWRITTEN
//

#import "IPadFactsView.h"

@interface IPadFactsView ()
@property (strong, nonatomic) NSMapTable *completionBlocksByAnimation;

@property (nonatomic, copy) void (^animationCompletionBlock)(void);

@end

@implementation IPadFactsView

#pragma mark - Life Cycle

- (instancetype)init
{
	return [self initWithFrame:CGRectMake(0,0,1024,768)];
}

- (instancetype)initWithFrame:(CGRect)frame
{
	self = [super initWithFrame:frame];
	if (self)
	{
		[self setupHierarchy];
	}
	return self;
}

- (instancetype)initWithCoder:(NSCoder *)coder
{
	self = [super initWithCoder:coder];
	if (self)
	{
		[self setupHierarchy];
	}
	return self;
}

#pragma mark - Scaling

- (void)layoutSubviews
{
	[super layoutSubviews];

	UIView *scalingView = self.viewsByName[@"__scaling__"];
	float xScale = self.bounds.size.width / scalingView.bounds.size.width;
	float yScale = self.bounds.size.height / scalingView.bounds.size.height;
	switch (self.contentMode) {
		case UIViewContentModeScaleToFill:
			break;
		case UIViewContentModeScaleAspectFill:
		{
			float scale = MAX(xScale, yScale);
			xScale = scale;
			yScale = scale;
			break;
		}
		default:
		{
			float scale = MIN(xScale, yScale);
			xScale = scale;
			yScale = scale;
			break;
		}
	}
	scalingView.transform = CGAffineTransformMakeScale(xScale, yScale);
	scalingView.center = CGPointMake(CGRectGetMidX(self.bounds), CGRectGetMidY(self.bounds));
}

#pragma mark - Customized animation and interaction

- (void)loadInAnimation {
    
    CAMediaTimingFunction *linearTiming = [CAMediaTimingFunction functionWithName:kCAMediaTimingFunctionLinear];
    CAMediaTimingFunction *easeOutTiming = [CAMediaTimingFunction functionWithName:kCAMediaTimingFunctionEaseOut];
    
    CFTimeInterval beginTime = 0;
    NSString *fillMode = kCAFillModeBoth;
    BOOL removedOnCompletion = YES;
    
    CAKeyframeAnimation *factGrid06SmOpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
    factGrid06SmOpacityAnimation.duration = 1.0;
    factGrid06SmOpacityAnimation.values = @[@(0.000), @(0.000), @(1.000)];
    factGrid06SmOpacityAnimation.keyTimes = @[@(0.000), @(0.050), @(0.200)];
    factGrid06SmOpacityAnimation.timingFunctions = @[linearTiming, easeOutTiming, linearTiming];
    factGrid06SmOpacityAnimation.beginTime = beginTime;
    factGrid06SmOpacityAnimation.fillMode = fillMode;
    factGrid06SmOpacityAnimation.removedOnCompletion = removedOnCompletion;
    [[self.viewsByName[@"fact-grid-06-sm"] layer] addAnimation:factGrid06SmOpacityAnimation forKey:@"Fade In Blocks_Opacity"];
    
    CAKeyframeAnimation *factGrid02SmOpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
    factGrid02SmOpacityAnimation.duration = 1.0;
    factGrid02SmOpacityAnimation.values = @[@(0.000), @(0.000), @(1.000)];
    factGrid02SmOpacityAnimation.keyTimes = @[@(0.000), @(0.200), @(0.400)];
    factGrid02SmOpacityAnimation.timingFunctions = @[linearTiming, easeOutTiming, linearTiming];
    factGrid02SmOpacityAnimation.beginTime = beginTime;
    factGrid02SmOpacityAnimation.fillMode = fillMode;
    factGrid02SmOpacityAnimation.removedOnCompletion = removedOnCompletion;
    [[self.viewsByName[@"fact-grid-02-sm"] layer] addAnimation:factGrid02SmOpacityAnimation forKey:@"Fade In Blocks_Opacity"];
    
    CAKeyframeAnimation *factGrid03SmOpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
    factGrid03SmOpacityAnimation.duration = 1.000;
    factGrid03SmOpacityAnimation.values = @[@(0.000), @(0.000), @(1.000)];
    factGrid03SmOpacityAnimation.keyTimes = @[@(0.000), @(0.150), @(0.300)];
    factGrid03SmOpacityAnimation.timingFunctions = @[linearTiming, easeOutTiming, linearTiming];
    factGrid03SmOpacityAnimation.beginTime = beginTime;
    factGrid03SmOpacityAnimation.fillMode = fillMode;
    factGrid03SmOpacityAnimation.removedOnCompletion = removedOnCompletion;
    [[self.viewsByName[@"fact-grid-03-sm"] layer] addAnimation:factGrid03SmOpacityAnimation forKey:@"Fade In Blocks_Opacity"];
    
    CAKeyframeAnimation *factGrid08SmOpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
    factGrid08SmOpacityAnimation.duration = 1.000;
    factGrid08SmOpacityAnimation.values = @[@(0.000), @(0.000), @(1.000)];
    factGrid08SmOpacityAnimation.keyTimes = @[@(0.000), @(0.100), @(0.200)];
    factGrid08SmOpacityAnimation.timingFunctions = @[linearTiming, easeOutTiming, linearTiming];
    factGrid08SmOpacityAnimation.beginTime = beginTime;
    factGrid08SmOpacityAnimation.fillMode = fillMode;
    factGrid08SmOpacityAnimation.removedOnCompletion = removedOnCompletion;
    [[self.viewsByName[@"fact-grid-08-sm"] layer] addAnimation:factGrid08SmOpacityAnimation forKey:@"Fade In Blocks_Opacity"];
    
    CAKeyframeAnimation *factGrid05SmOpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
    factGrid05SmOpacityAnimation.duration = 1.000;
    factGrid05SmOpacityAnimation.values = @[@(0.000), @(0.000), @(1.000)];
    factGrid05SmOpacityAnimation.keyTimes = @[@(0.000), @(0.150), @(0.300)];
    factGrid05SmOpacityAnimation.timingFunctions = @[linearTiming, easeOutTiming, linearTiming];
    factGrid05SmOpacityAnimation.beginTime = beginTime;
    factGrid05SmOpacityAnimation.fillMode = fillMode;
    factGrid05SmOpacityAnimation.removedOnCompletion = removedOnCompletion;
    [[self.viewsByName[@"fact-grid-05-sm"] layer] addAnimation:factGrid05SmOpacityAnimation forKey:@"Fade In Blocks_Opacity"];
    
    CAKeyframeAnimation *factGrid04SmOpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
    factGrid04SmOpacityAnimation.duration = 1.000;
    factGrid04SmOpacityAnimation.values = @[@(0.000), @(0.000), @(1.000)];
    factGrid04SmOpacityAnimation.keyTimes = @[@(0.000), @(0.200), @(0.400)];
    factGrid04SmOpacityAnimation.timingFunctions = @[linearTiming, easeOutTiming, linearTiming];
    factGrid04SmOpacityAnimation.beginTime = beginTime;
    factGrid04SmOpacityAnimation.fillMode = fillMode;
    factGrid04SmOpacityAnimation.removedOnCompletion = removedOnCompletion;
    [[self.viewsByName[@"fact-grid-04-sm"] layer] addAnimation:factGrid04SmOpacityAnimation forKey:@"Fade In Blocks_Opacity"];
    
    CAKeyframeAnimation *factGrid09SmOpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
    factGrid09SmOpacityAnimation.duration = 1.000;
    factGrid09SmOpacityAnimation.values = @[@(0.000), @(0.000), @(1.000)];
    factGrid09SmOpacityAnimation.keyTimes = @[@(0.000), @(0.050), @(0.100)];
    factGrid09SmOpacityAnimation.timingFunctions = @[linearTiming, easeOutTiming, linearTiming];
    factGrid09SmOpacityAnimation.beginTime = beginTime;
    factGrid09SmOpacityAnimation.fillMode = fillMode;
    factGrid09SmOpacityAnimation.removedOnCompletion = removedOnCompletion;
    [[self.viewsByName[@"fact-grid-09-sm"] layer] addAnimation:factGrid09SmOpacityAnimation forKey:@"Fade In Blocks_Opacity"];
    
    CAKeyframeAnimation *factGrid07SmOpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
    factGrid07SmOpacityAnimation.duration = 1.000;
    factGrid07SmOpacityAnimation.values = @[@(0.000), @(0.000), @(1.000)];
    factGrid07SmOpacityAnimation.keyTimes = @[@(0.000), @(0.150), @(0.300)];
    factGrid07SmOpacityAnimation.timingFunctions = @[linearTiming, easeOutTiming, linearTiming];
    factGrid07SmOpacityAnimation.beginTime = beginTime;
    factGrid07SmOpacityAnimation.fillMode = fillMode;
    factGrid07SmOpacityAnimation.removedOnCompletion = removedOnCompletion;
    [[self.viewsByName[@"fact-grid-07-sm"] layer] addAnimation:factGrid07SmOpacityAnimation forKey:@"Fade In Blocks_Opacity"];
    
    CAKeyframeAnimation *factGrid01SmOpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
    factGrid01SmOpacityAnimation.duration = 1.000;
    factGrid01SmOpacityAnimation.values = @[@(0.000), @(0.000), @(1.000)];
    factGrid01SmOpacityAnimation.keyTimes = @[@(0.000), @(0.250), @(0.500)];
    factGrid01SmOpacityAnimation.timingFunctions = @[linearTiming, easeOutTiming, linearTiming];
    factGrid01SmOpacityAnimation.beginTime = beginTime;
    factGrid01SmOpacityAnimation.fillMode = fillMode;
    factGrid01SmOpacityAnimation.removedOnCompletion = removedOnCompletion;
    [[self.viewsByName[@"fact-grid-01-sm"] layer] addAnimation:factGrid01SmOpacityAnimation forKey:@"Fade In Blocks_Opacity"];
    
    __weak typeof(self) weakSelf = self;
    [self setAnimationCompletionBlock:^(void){
        [weakSelf.viewsByName[@"fact-grid-01-sm"] layer].opacity = 1.0;
        [weakSelf.viewsByName[@"fact-grid-02-sm"] layer].opacity = 1.0;
        [weakSelf.viewsByName[@"fact-grid-03-sm"] layer].opacity = 1.0;
        [weakSelf.viewsByName[@"fact-grid-04-sm"] layer].opacity = 1.0;
        [weakSelf.viewsByName[@"fact-grid-05-sm"] layer].opacity = 1.0;
        [weakSelf.viewsByName[@"fact-grid-06-sm"] layer].opacity = 1.0;
        [weakSelf.viewsByName[@"fact-grid-07-sm"] layer].opacity = 1.0;
        [weakSelf.viewsByName[@"fact-grid-08-sm"] layer].opacity = 1.0;
        [weakSelf.viewsByName[@"fact-grid-09-sm"] layer].opacity = 1.0;
    }];
    
    CABasicAnimation *representativeAnimation = [CABasicAnimation animationWithKeyPath:@"not.a.real.key"];
    representativeAnimation.duration = 1.000;
    representativeAnimation.delegate = self;
    [self.layer addAnimation:representativeAnimation forKey:@"FadeInBlocks"];
    [self.completionBlocksByAnimation setObject:self.animationCompletionBlock forKey:[self.layer animationForKey:@"FadeInBlocks"]];
}

- (void)addGestureToView:(UIView *)targetView {
    UITapGestureRecognizer *tapOnView = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(tapOnView:)];
    targetView.userInteractionEnabled = YES;
    [targetView addGestureRecognizer: tapOnView];
}

- (void)tapOnView:(UIGestureRecognizer *)gesture {
    
    NSLog(@"\n\nasdflas;ldfjsadjfl;asl;dfjas;ldfj\n\n");
    
    CAMediaTimingFunction *linearTiming = [CAMediaTimingFunction functionWithName:kCAMediaTimingFunctionLinear];
    
    CFTimeInterval beginTime = 0;
    NSString *fillMode = kCAFillModeBoth;
    BOOL removedOnCompletion = NO;
    
    CAKeyframeAnimation *factGrid01SmScaleXAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.scale.x"];
    factGrid01SmScaleXAnimation.duration = 0.5;
    factGrid01SmScaleXAnimation.values = @[@(1.000), @(3.047)];
    factGrid01SmScaleXAnimation.keyTimes = @[@(0.000), @(1.000)];
    factGrid01SmScaleXAnimation.timingFunctions = @[linearTiming, linearTiming];
    factGrid01SmScaleXAnimation.beginTime = beginTime;
    factGrid01SmScaleXAnimation.fillMode = fillMode;
    factGrid01SmScaleXAnimation.removedOnCompletion = removedOnCompletion;
    [[self.viewsByName[@"fact-grid-01-sm"] layer] addAnimation:factGrid01SmScaleXAnimation forKey:@"Fade In Blocks_ScaleX"];
    
    CAKeyframeAnimation *factGrid01SmScaleYAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.scale.y"];
    factGrid01SmScaleYAnimation.duration = 0.5;
    factGrid01SmScaleYAnimation.values = @[@(1.000), @(3.047)];
    factGrid01SmScaleYAnimation.keyTimes = @[@(0.000), @(1.000)];
    factGrid01SmScaleYAnimation.timingFunctions = @[linearTiming, linearTiming, linearTiming, linearTiming, linearTiming, linearTiming];
    factGrid01SmScaleYAnimation.beginTime = beginTime;
    factGrid01SmScaleYAnimation.fillMode = fillMode;
    factGrid01SmScaleYAnimation.removedOnCompletion = removedOnCompletion;
    [[self.viewsByName[@"fact-grid-01-sm"] layer] addAnimation:factGrid01SmScaleYAnimation forKey:@"Fade In Blocks_ScaleY"];
    
    CAKeyframeAnimation *factGrid01SmTranslationXAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.translation.x"];
    factGrid01SmTranslationXAnimation.duration = 0.5;
    factGrid01SmTranslationXAnimation.values = @[@(0.000), @(119.748)];
    factGrid01SmTranslationXAnimation.keyTimes = @[@(0.000), @(1.000)];
    factGrid01SmTranslationXAnimation.timingFunctions = @[linearTiming, linearTiming];
    factGrid01SmTranslationXAnimation.beginTime = beginTime;
    factGrid01SmTranslationXAnimation.fillMode = fillMode;
    factGrid01SmTranslationXAnimation.removedOnCompletion = removedOnCompletion;
    [[self.viewsByName[@"fact-grid-01-sm"] layer] addAnimation:factGrid01SmTranslationXAnimation forKey:@"Fade In Blocks_TranslationX"];
    
    CAKeyframeAnimation *factGrid01SmTranslationYAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.translation.y"];
    factGrid01SmTranslationYAnimation.duration = 0.5;
    factGrid01SmTranslationYAnimation.values = @[@(0.000), @(119.748)];
    factGrid01SmTranslationYAnimation.keyTimes = @[@(0.000), @(1.000)];
    factGrid01SmTranslationYAnimation.timingFunctions = @[linearTiming, linearTiming];
    factGrid01SmTranslationYAnimation.beginTime = beginTime;
    factGrid01SmTranslationYAnimation.fillMode = fillMode;
    factGrid01SmTranslationYAnimation.removedOnCompletion = removedOnCompletion;
    [[self.viewsByName[@"fact-grid-01-sm"] layer] addAnimation:factGrid01SmTranslationYAnimation forKey:@"Fade In Blocks_TranslationY"];
    
    CAKeyframeAnimation *factCopy01OpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
    factCopy01OpacityAnimation.duration = 0.5;
    factCopy01OpacityAnimation.values = @[@(0.000), @(1.000)];
    factCopy01OpacityAnimation.keyTimes = @[@(0.000), @(1.000)];
    factCopy01OpacityAnimation.timingFunctions = @[linearTiming, linearTiming];
    factCopy01OpacityAnimation.beginTime = beginTime;
    factCopy01OpacityAnimation.fillMode = fillMode;
    factCopy01OpacityAnimation.removedOnCompletion = removedOnCompletion;
    [[self.viewsByName[@"fact-copy-01"] layer] addAnimation:factCopy01OpacityAnimation forKey:@"Fade In Blocks_Opacity"];
    
    CAKeyframeAnimation *factCopy01TranslationXAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.translation.x"];
    factCopy01TranslationXAnimation.duration = 0.5;
    factCopy01TranslationXAnimation.values = @[@(0.000), @(-29.020)];
    factCopy01TranslationXAnimation.keyTimes = @[@(0.000), @(1.000)];
    factCopy01TranslationXAnimation.timingFunctions = @[linearTiming, linearTiming];
    factCopy01TranslationXAnimation.beginTime = beginTime;
    factCopy01TranslationXAnimation.fillMode = fillMode;
    factCopy01TranslationXAnimation.removedOnCompletion = removedOnCompletion;
    [[self.viewsByName[@"fact-copy-01"] layer] addAnimation:factCopy01TranslationXAnimation forKey:@"Fade In Blocks_TranslationX"];
    
    CAKeyframeAnimation *grfxFactBgOpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
    grfxFactBgOpacityAnimation.duration = 0.5;
    grfxFactBgOpacityAnimation.values = @[@(0.000), @(1.000)];
    grfxFactBgOpacityAnimation.keyTimes = @[@(0.000), @(1.000)];
    grfxFactBgOpacityAnimation.timingFunctions = @[linearTiming, linearTiming];
    grfxFactBgOpacityAnimation.beginTime = beginTime;
    grfxFactBgOpacityAnimation.fillMode = fillMode;
    grfxFactBgOpacityAnimation.removedOnCompletion = removedOnCompletion;
    [[self.viewsByName[@"grfx-fact-bg"] layer] addAnimation:grfxFactBgOpacityAnimation forKey:@"Fade In Blocks_Opacity"];
    
    CAKeyframeAnimation *grfxFactBgTranslationXAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.translation.x"];
    grfxFactBgTranslationXAnimation.duration = 0.5;
    grfxFactBgTranslationXAnimation.values = @[@(0.000), @(250.000)];
    grfxFactBgTranslationXAnimation.keyTimes = @[@(0.000), @(1.0)];
    grfxFactBgTranslationXAnimation.timingFunctions = @[linearTiming, linearTiming];
    grfxFactBgTranslationXAnimation.beginTime = beginTime;
    grfxFactBgTranslationXAnimation.fillMode = fillMode;
    grfxFactBgTranslationXAnimation.removedOnCompletion = removedOnCompletion;
    [[self.viewsByName[@"grfx-fact-bg"] layer] addAnimation:grfxFactBgTranslationXAnimation forKey:@"Fade In Blocks_TranslationX"];
}

#pragma mark - Setup

- (void)setupHierarchy
{
	self.completionBlocksByAnimation = [NSMapTable mapTableWithKeyOptions:NSPointerFunctionsOpaqueMemory valueOptions:NSPointerFunctionsStrongMemory];
	NSMutableDictionary *viewsByName = [NSMutableDictionary dictionary];
	NSBundle *bundle = [NSBundle bundleForClass:[self class]];

	UIView *__scaling__ = [UIView new];
	__scaling__.bounds = CGRectMake(0, 0, 1024, 768);
	__scaling__.center = CGPointMake(512.0, 384.0);
	__scaling__.layer.masksToBounds = YES;
	[self addSubview:__scaling__];
	viewsByName[@"__scaling__"] = __scaling__;

	UIImageView *bg = [UIImageView new];
	bg.bounds = CGRectMake(0, 0, 1024.0, 768.0);
	UIImage *imgBg = [UIImage imageWithContentsOfFile:[bundle pathForResource:@"bg.jpg" ofType:nil]];
	bg.image = imgBg;
	bg.contentMode = UIViewContentModeCenter;
	bg.layer.position = CGPointMake(512.000, 384.000);
	[__scaling__ addSubview:bg];
	viewsByName[@"bg"] = bg;

	UIImageView *grfxFactBg = [UIImageView new];
	grfxFactBg.bounds = CGRectMake(0, 0, 360.0, 360.0);
	UIImage *imgGrfxFactBg = [UIImage imageWithContentsOfFile:[bundle pathForResource:@"grfx-fact-bg.png" ofType:nil]];
	grfxFactBg.image = imgGrfxFactBg;
	grfxFactBg.contentMode = UIViewContentModeCenter;
	grfxFactBg.layer.position = CGPointMake(202.000, 384.000);
    grfxFactBg.backgroundColor = [UIColor greenColor];
	[__scaling__ addSubview:grfxFactBg];
	viewsByName[@"grfx-fact-bg"] = grfxFactBg;

	UIImageView *factGrid01Sm = [UIImageView new];
	factGrid01Sm.bounds = CGRectMake(0, 0, 117.0, 117.0);
	UIImage *imgFactGrid01Sm = [UIImage imageWithContentsOfFile:[bundle pathForResource:@"fact-grid-01-sm.png" ofType:nil]];
	factGrid01Sm.image = imgFactGrid01Sm;
	factGrid01Sm.contentMode = UIViewContentModeCenter;
	factGrid01Sm.layer.position = CGPointMake(80.786, 264.513);
	[__scaling__ addSubview:factGrid01Sm];
	viewsByName[@"fact-grid-01-sm"] = factGrid01Sm;
    factGrid01Sm.backgroundColor = [UIColor redColor];
    [self addGestureToView:factGrid01Sm];
    factGrid01Sm.layer.opacity = 0.0;

	UIImageView *factGrid02Sm = [UIImageView new];
	factGrid02Sm.bounds = CGRectMake(0, 0, 117.0, 117.0);
	UIImage *imgFactGrid02Sm = [UIImage imageWithContentsOfFile:[bundle pathForResource:@"fact-grid-02-sm.png" ofType:nil]];
	factGrid02Sm.image = imgFactGrid02Sm;
	factGrid02Sm.contentMode = UIViewContentModeCenter;
	factGrid02Sm.layer.position = CGPointMake(200.786, 264.513);
	[__scaling__ addSubview:factGrid02Sm];
	viewsByName[@"fact-grid-02-sm"] = factGrid02Sm;
    factGrid02Sm.backgroundColor = [UIColor redColor];
    [self addGestureToView:factGrid02Sm];
    factGrid02Sm.layer.opacity = 0.0;

	UIImageView *factGrid03Sm = [UIImageView new];
	factGrid03Sm.bounds = CGRectMake(0, 0, 117.0, 117.0);
	UIImage *imgFactGrid03Sm = [UIImage imageWithContentsOfFile:[bundle pathForResource:@"fact-grid-03-sm.png" ofType:nil]];
	factGrid03Sm.image = imgFactGrid03Sm;
	factGrid03Sm.contentMode = UIViewContentModeCenter;
	factGrid03Sm.layer.position = CGPointMake(320.786, 264.513);
	[__scaling__ addSubview:factGrid03Sm];
	viewsByName[@"fact-grid-03-sm"] = factGrid03Sm;
    factGrid03Sm.backgroundColor = [UIColor redColor];
    [self addGestureToView:factGrid03Sm];
    factGrid03Sm.layer.opacity = 0.0;

	UIImageView *factGrid04Sm = [UIImageView new];
	factGrid04Sm.bounds = CGRectMake(0, 0, 117.0, 117.0);
	UIImage *imgFactGrid04Sm = [UIImage imageWithContentsOfFile:[bundle pathForResource:@"fact-grid-04-sm.png" ofType:nil]];
	factGrid04Sm.image = imgFactGrid04Sm;
	factGrid04Sm.contentMode = UIViewContentModeCenter;
	factGrid04Sm.layer.position = CGPointMake(80.786, 384.513);
	[__scaling__ addSubview:factGrid04Sm];
	viewsByName[@"fact-grid-04-sm"] = factGrid04Sm;
    factGrid04Sm.backgroundColor = [UIColor redColor];
    [self addGestureToView:factGrid04Sm];
    factGrid04Sm.layer.opacity = 0.0;

	UIImageView *factGrid05Sm = [UIImageView new];
	factGrid05Sm.bounds = CGRectMake(0, 0, 117.0, 117.0);
	UIImage *imgFactGrid05Sm = [UIImage imageWithContentsOfFile:[bundle pathForResource:@"fact-grid-05-sm.png" ofType:nil]];
	factGrid05Sm.image = imgFactGrid05Sm;
	factGrid05Sm.contentMode = UIViewContentModeCenter;
	factGrid05Sm.layer.position = CGPointMake(200.786, 384.513);
	[__scaling__ addSubview:factGrid05Sm];
	viewsByName[@"fact-grid-05-sm"] = factGrid05Sm;
    factGrid05Sm.backgroundColor = [UIColor redColor];
    [self addGestureToView:factGrid05Sm];
    factGrid05Sm.layer.opacity = 0.0;

	UIImageView *factGrid06Sm = [UIImageView new];
	factGrid06Sm.bounds = CGRectMake(0, 0, 117.0, 117.0);
	UIImage *imgFactGrid06Sm = [UIImage imageWithContentsOfFile:[bundle pathForResource:@"fact-grid-06-sm.png" ofType:nil]];
	factGrid06Sm.image = imgFactGrid06Sm;
	factGrid06Sm.contentMode = UIViewContentModeCenter;
	factGrid06Sm.layer.position = CGPointMake(320.786, 384.513);
	[__scaling__ addSubview:factGrid06Sm];
	viewsByName[@"fact-grid-06-sm"] = factGrid06Sm;
    factGrid06Sm.backgroundColor = [UIColor redColor];
    [self addGestureToView:factGrid06Sm];
    factGrid06Sm.layer.opacity = 0.0;

	UIImageView *factGrid07Sm = [UIImageView new];
	factGrid07Sm.bounds = CGRectMake(0, 0, 117.0, 117.0);
	UIImage *imgFactGrid07Sm = [UIImage imageWithContentsOfFile:[bundle pathForResource:@"fact-grid-07-sm.png" ofType:nil]];
	factGrid07Sm.image = imgFactGrid07Sm;
	factGrid07Sm.contentMode = UIViewContentModeCenter;
	factGrid07Sm.layer.position = CGPointMake(80.786, 504.513);
	[__scaling__ addSubview:factGrid07Sm];
	viewsByName[@"fact-grid-07-sm"] = factGrid07Sm;
    factGrid07Sm.backgroundColor = [UIColor redColor];
    [self addGestureToView:factGrid07Sm];
    factGrid07Sm.layer.opacity = 0.0;

	UIImageView *factGrid08Sm = [UIImageView new];
	factGrid08Sm.bounds = CGRectMake(0, 0, 117.0, 117.0);
	UIImage *imgFactGrid08Sm = [UIImage imageWithContentsOfFile:[bundle pathForResource:@"fact-grid-08-sm.png" ofType:nil]];
	factGrid08Sm.image = imgFactGrid08Sm;
	factGrid08Sm.contentMode = UIViewContentModeCenter;
	factGrid08Sm.layer.position = CGPointMake(200.786, 504.513);
	[__scaling__ addSubview:factGrid08Sm];
	viewsByName[@"fact-grid-08-sm"] = factGrid08Sm;
    factGrid08Sm.backgroundColor = [UIColor redColor];
    [self addGestureToView:factGrid08Sm];
    factGrid08Sm.layer.opacity = 0.0;

	UIImageView *factGrid01Lg = [UIImageView new];
	factGrid01Lg.bounds = CGRectMake(0, 0, 360.0, 360.0);
	UIImage *imgFactGrid01Lg = [UIImage imageWithContentsOfFile:[bundle pathForResource:@"fact-grid-01-lg.png" ofType:nil]];
	factGrid01Lg.image = imgFactGrid01Lg;
	factGrid01Lg.contentMode = UIViewContentModeCenter;
	factGrid01Lg.layer.position = CGPointMake(202.000, 384.000);
	[__scaling__ addSubview:factGrid01Lg];
	viewsByName[@"fact-grid-01-lg"] = factGrid01Lg;

	UIImageView *grfxArrowRight = [UIImageView new];
	grfxArrowRight.bounds = CGRectMake(0, 0, 18.0, 18.0);
	UIImage *imgGrfxArrowRight = [UIImage imageWithContentsOfFile:[bundle pathForResource:@"grfx-arrow-right.png" ofType:nil]];
	grfxArrowRight.image = imgGrfxArrowRight;
	grfxArrowRight.contentMode = UIViewContentModeCenter;
	grfxArrowRight.layer.position = CGPointMake(382.000, 384.000);
	[__scaling__ addSubview:grfxArrowRight];
	viewsByName[@"grfx-arrow-right"] = grfxArrowRight;

	UIImageView *factGrid09Sm = [UIImageView new];
	factGrid09Sm.bounds = CGRectMake(0, 0, 117.0, 117.0);
	UIImage *imgFactGrid09Sm = [UIImage imageWithContentsOfFile:[bundle pathForResource:@"fact-grid-09-sm.png" ofType:nil]];
	factGrid09Sm.image = imgFactGrid09Sm;
	factGrid09Sm.contentMode = UIViewContentModeCenter;
	factGrid09Sm.layer.position = CGPointMake(320.786, 504.513);
	[__scaling__ addSubview:factGrid09Sm];
	viewsByName[@"fact-grid-09-sm"] = factGrid09Sm;
    factGrid09Sm.backgroundColor = [UIColor redColor];
    [self addGestureToView:factGrid09Sm];
    factGrid09Sm.layer.opacity = 0.0;

	UIImageView *factCopy01 = [UIImageView new];
	factCopy01.bounds = CGRectMake(0, 0, 271.0, 167.0);
	UIImage *imgFactCopy01 = [UIImage imageWithContentsOfFile:[bundle pathForResource:@"fact-copy-01.png" ofType:nil]];
	factCopy01.image = imgFactCopy01;
	factCopy01.contentMode = UIViewContentModeCenter;
	factCopy01.layer.position = CGPointMake(522.000, 384.000);
	[__scaling__ addSubview:factCopy01];
	viewsByName[@"fact-copy-01"] = factCopy01;
    factCopy01.backgroundColor = [UIColor blueColor];

	UIImageView *grfxArrowLeft = [UIImageView new];
	grfxArrowLeft.bounds = CGRectMake(0, 0, 18.0, 18.0);
	UIImage *imgGrfxArrowLeft = [UIImage imageWithContentsOfFile:[bundle pathForResource:@"grfx-arrow-left.png" ofType:nil]];
	grfxArrowLeft.image = imgGrfxArrowLeft;
	grfxArrowLeft.contentMode = UIViewContentModeCenter;
	grfxArrowLeft.layer.position = CGPointMake(382.000, 384.000);
	[__scaling__ addSubview:grfxArrowLeft];
	viewsByName[@"grfx-arrow-left"] = grfxArrowLeft;

	UIImageView *grfxIconGrid = [UIImageView new];
	grfxIconGrid.bounds = CGRectMake(0, 0, 17.0, 17.0);
	UIImage *imgGrfxIconGrid = [UIImage imageWithContentsOfFile:[bundle pathForResource:@"grfx-icon-grid.png" ofType:nil]];
	grfxIconGrid.image = imgGrfxIconGrid;
	grfxIconGrid.contentMode = UIViewContentModeCenter;
	grfxIconGrid.layer.position = CGPointMake(360.000, 229.000);
	[__scaling__ addSubview:grfxIconGrid];
	viewsByName[@"grfx-icon-grid"] = grfxIconGrid;
    grfxIconGrid.backgroundColor = [UIColor blackColor];

	self.viewsByName = viewsByName;
}

#pragma mark - Fade In Blocks

- (void)addFadeInBlocksAnimation
{
	[self addFadeInBlocksAnimationWithBeginTime:0 andFillMode:kCAFillModeBoth andRemoveOnCompletion:NO completion:NULL];
}

- (void)addFadeInBlocksAnimationWithCompletion:(void (^)(BOOL finished))completionBlock
{
	[self addFadeInBlocksAnimationWithBeginTime:0 andFillMode:kCAFillModeBoth andRemoveOnCompletion:NO completion:completionBlock];
}

- (void)addFadeInBlocksAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion
{
	[self addFadeInBlocksAnimationWithBeginTime:0 andFillMode:removedOnCompletion ? kCAFillModeRemoved : kCAFillModeBoth andRemoveOnCompletion:removedOnCompletion completion:NULL];
}

- (void)addFadeInBlocksAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock
{
	[self addFadeInBlocksAnimationWithBeginTime:0 andFillMode:removedOnCompletion ? kCAFillModeRemoved : kCAFillModeBoth andRemoveOnCompletion:removedOnCompletion completion:completionBlock];
}

- (void)addFadeInBlocksAnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode andRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock
{
	CAMediaTimingFunction *linearTiming = [CAMediaTimingFunction functionWithName:kCAMediaTimingFunctionLinear];
	CAMediaTimingFunction *easeOutTiming = [CAMediaTimingFunction functionWithName:kCAMediaTimingFunctionEaseOut];

	if (completionBlock)
	{
		CABasicAnimation *representativeAnimation = [CABasicAnimation animationWithKeyPath:@"not.a.real.key"];
		representativeAnimation.duration = 6.500;
		representativeAnimation.delegate = self;
		[self.layer addAnimation:representativeAnimation forKey:@"FadeInBlocks"];
		[self.completionBlocksByAnimation setObject:completionBlock forKey:[self.layer animationForKey:@"FadeInBlocks"]];
	}

	CAKeyframeAnimation *grfxArrowRightOpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
	grfxArrowRightOpacityAnimation.duration = 6.500;
	grfxArrowRightOpacityAnimation.values = @[@(0.000), @(0.000), @(1.000), @(1.000)];
	grfxArrowRightOpacityAnimation.keyTimes = @[@(0.000), @(0.269), @(0.354), @(1.000)];
	grfxArrowRightOpacityAnimation.timingFunctions = @[linearTiming, linearTiming, linearTiming];
	grfxArrowRightOpacityAnimation.beginTime = beginTime;
	grfxArrowRightOpacityAnimation.fillMode = fillMode;
	grfxArrowRightOpacityAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"grfx-arrow-right"] layer] addAnimation:grfxArrowRightOpacityAnimation forKey:@"Fade In Blocks_Opacity"];

	CAKeyframeAnimation *grfxArrowRightTranslationXAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.translation.x"];
	grfxArrowRightTranslationXAnimation.duration = 6.500;
	grfxArrowRightTranslationXAnimation.values = @[@(-30.000), @(20.000), @(0.000), @(0.000), @(250.000), @(250.000)];
	grfxArrowRightTranslationXAnimation.keyTimes = @[@(0.000), @(0.354), @(0.385), @(0.638), @(0.692), @(1.000)];
	grfxArrowRightTranslationXAnimation.timingFunctions = @[linearTiming, linearTiming, linearTiming, linearTiming, linearTiming];
	grfxArrowRightTranslationXAnimation.beginTime = beginTime;
	grfxArrowRightTranslationXAnimation.fillMode = fillMode;
	grfxArrowRightTranslationXAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"grfx-arrow-right"] layer] addAnimation:grfxArrowRightTranslationXAnimation forKey:@"Fade In Blocks_TranslationX"];

	CAKeyframeAnimation *factGrid06SmOpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
	factGrid06SmOpacityAnimation.duration = 6.500;
	factGrid06SmOpacityAnimation.values = @[@(0.000), @(0.000), @(1.000), @(1.000), @(0.000), @(0.000), @(0.000), @(1.000), @(1.000)];
	factGrid06SmOpacityAnimation.keyTimes = @[@(0.000), @(0.015), @(0.031), @(0.308), @(0.323), @(0.923), @(0.969), @(0.985), @(1.000)];
	factGrid06SmOpacityAnimation.timingFunctions = @[linearTiming, easeOutTiming, linearTiming, linearTiming, linearTiming, linearTiming, linearTiming, linearTiming];
	factGrid06SmOpacityAnimation.beginTime = beginTime;
	factGrid06SmOpacityAnimation.fillMode = fillMode;
	factGrid06SmOpacityAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"fact-grid-06-sm"] layer] addAnimation:factGrid06SmOpacityAnimation forKey:@"Fade In Blocks_Opacity"];

	CAKeyframeAnimation *factGrid02SmOpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
	factGrid02SmOpacityAnimation.duration = 6.500;
	factGrid02SmOpacityAnimation.values = @[@(0.000), @(0.000), @(1.000), @(1.000), @(0.000), @(0.000), @(0.000), @(1.000)];
	factGrid02SmOpacityAnimation.keyTimes = @[@(0.000), @(0.046), @(0.062), @(0.308), @(0.323), @(0.923), @(0.985), @(1.000)];
	factGrid02SmOpacityAnimation.timingFunctions = @[linearTiming, easeOutTiming, linearTiming, linearTiming, linearTiming, linearTiming, linearTiming];
	factGrid02SmOpacityAnimation.beginTime = beginTime;
	factGrid02SmOpacityAnimation.fillMode = fillMode;
	factGrid02SmOpacityAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"fact-grid-02-sm"] layer] addAnimation:factGrid02SmOpacityAnimation forKey:@"Fade In Blocks_Opacity"];

	CAKeyframeAnimation *factGrid03SmOpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
	factGrid03SmOpacityAnimation.duration = 6.500;
	factGrid03SmOpacityAnimation.values = @[@(0.000), @(0.000), @(1.000), @(1.000), @(0.000), @(0.000), @(0.000), @(1.000), @(1.000)];
	factGrid03SmOpacityAnimation.keyTimes = @[@(0.000), @(0.031), @(0.046), @(0.308), @(0.323), @(0.923), @(0.977), @(0.992), @(1.000)];
	factGrid03SmOpacityAnimation.timingFunctions = @[linearTiming, easeOutTiming, linearTiming, linearTiming, linearTiming, linearTiming, linearTiming, linearTiming];
	factGrid03SmOpacityAnimation.beginTime = beginTime;
	factGrid03SmOpacityAnimation.fillMode = fillMode;
	factGrid03SmOpacityAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"fact-grid-03-sm"] layer] addAnimation:factGrid03SmOpacityAnimation forKey:@"Fade In Blocks_Opacity"];

	CAKeyframeAnimation *factCopy01OpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
	factCopy01OpacityAnimation.duration = 6.500;
	factCopy01OpacityAnimation.values = @[@(0.000), @(0.000), @(1.000), @(1.000), @(0.000), @(0.000)];
	factCopy01OpacityAnimation.keyTimes = @[@(0.000), @(0.692), @(0.708), @(0.923), @(0.931), @(1.000)];
	factCopy01OpacityAnimation.timingFunctions = @[linearTiming, linearTiming, linearTiming, linearTiming, linearTiming];
	factCopy01OpacityAnimation.beginTime = beginTime;
	factCopy01OpacityAnimation.fillMode = fillMode;
	factCopy01OpacityAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"fact-copy-01"] layer] addAnimation:factCopy01OpacityAnimation forKey:@"Fade In Blocks_Opacity"];

	CAKeyframeAnimation *factCopy01TranslationXAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.translation.x"];
	factCopy01TranslationXAnimation.duration = 6.500;
	factCopy01TranslationXAnimation.values = @[@(0.000), @(-29.020), @(-50.000), @(-50.000), @(-60.000), @(-60.000)];
	factCopy01TranslationXAnimation.keyTimes = @[@(0.000), @(0.692), @(0.708), @(0.923), @(0.931), @(1.000)];
	factCopy01TranslationXAnimation.timingFunctions = @[linearTiming, linearTiming, linearTiming, linearTiming, linearTiming];
	factCopy01TranslationXAnimation.beginTime = beginTime;
	factCopy01TranslationXAnimation.fillMode = fillMode;
	factCopy01TranslationXAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"fact-copy-01"] layer] addAnimation:factCopy01TranslationXAnimation forKey:@"Fade In Blocks_TranslationX"];

	CAKeyframeAnimation *factGrid08SmOpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
	factGrid08SmOpacityAnimation.duration = 6.500;
	factGrid08SmOpacityAnimation.values = @[@(0.000), @(0.000), @(1.000), @(1.000), @(0.000), @(0.000), @(0.000), @(0.000), @(1.000), @(1.000)];
	factGrid08SmOpacityAnimation.keyTimes = @[@(0.000), @(0.015), @(0.031), @(0.308), @(0.323), @(0.923), @(0.938), @(0.969), @(0.985), @(1.000)];
	factGrid08SmOpacityAnimation.timingFunctions = @[linearTiming, easeOutTiming, linearTiming, linearTiming, linearTiming, linearTiming, linearTiming, linearTiming, linearTiming];
	factGrid08SmOpacityAnimation.beginTime = beginTime;
	factGrid08SmOpacityAnimation.fillMode = fillMode;
	factGrid08SmOpacityAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"fact-grid-08-sm"] layer] addAnimation:factGrid08SmOpacityAnimation forKey:@"Fade In Blocks_Opacity"];

	CAKeyframeAnimation *grfxFactBgOpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
	grfxFactBgOpacityAnimation.duration = 6.500;
	grfxFactBgOpacityAnimation.values = @[@(0.000), @(0.000), @(1.000), @(1.000), @(1.000), @(1.000), @(0.000), @(0.000)];
	grfxFactBgOpacityAnimation.keyTimes = @[@(0.000), @(0.523), @(0.538), @(0.546), @(0.923), @(0.923), @(0.938), @(1.000)];
	grfxFactBgOpacityAnimation.timingFunctions = @[linearTiming, linearTiming, linearTiming, linearTiming, linearTiming, linearTiming, linearTiming];
	grfxFactBgOpacityAnimation.beginTime = beginTime;
	grfxFactBgOpacityAnimation.fillMode = fillMode;
	grfxFactBgOpacityAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"grfx-fact-bg"] layer] addAnimation:grfxFactBgOpacityAnimation forKey:@"Fade In Blocks_Opacity"];

	CAKeyframeAnimation *grfxFactBgTranslationXAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.translation.x"];
	grfxFactBgTranslationXAnimation.duration = 6.500;
	grfxFactBgTranslationXAnimation.values = @[@(0.000), @(0.000), @(250.000), @(250.000), @(0.000), @(0.000)];
	grfxFactBgTranslationXAnimation.keyTimes = @[@(0.000), @(0.638), @(0.692), @(0.923), @(0.938), @(1.000)];
	grfxFactBgTranslationXAnimation.timingFunctions = @[linearTiming, linearTiming, linearTiming, linearTiming, linearTiming];
	grfxFactBgTranslationXAnimation.beginTime = beginTime;
	grfxFactBgTranslationXAnimation.fillMode = fillMode;
	grfxFactBgTranslationXAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"grfx-fact-bg"] layer] addAnimation:grfxFactBgTranslationXAnimation forKey:@"Fade In Blocks_TranslationX"];

	CAKeyframeAnimation *factGrid05SmOpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
	factGrid05SmOpacityAnimation.duration = 6.500;
	factGrid05SmOpacityAnimation.values = @[@(0.000), @(0.000), @(1.000), @(1.000), @(0.000), @(0.000), @(0.000), @(1.000), @(1.000)];
	factGrid05SmOpacityAnimation.keyTimes = @[@(0.000), @(0.031), @(0.046), @(0.308), @(0.323), @(0.923), @(0.977), @(0.992), @(1.000)];
	factGrid05SmOpacityAnimation.timingFunctions = @[linearTiming, easeOutTiming, linearTiming, linearTiming, linearTiming, linearTiming, linearTiming, linearTiming];
	factGrid05SmOpacityAnimation.beginTime = beginTime;
	factGrid05SmOpacityAnimation.fillMode = fillMode;
	factGrid05SmOpacityAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"fact-grid-05-sm"] layer] addAnimation:factGrid05SmOpacityAnimation forKey:@"Fade In Blocks_Opacity"];

	CAKeyframeAnimation *factGrid04SmOpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
	factGrid04SmOpacityAnimation.duration = 6.500;
	factGrid04SmOpacityAnimation.values = @[@(0.000), @(0.000), @(1.000), @(1.000), @(0.000), @(0.000), @(0.000), @(1.000)];
	factGrid04SmOpacityAnimation.keyTimes = @[@(0.000), @(0.046), @(0.062), @(0.308), @(0.323), @(0.923), @(0.985), @(1.000)];
	factGrid04SmOpacityAnimation.timingFunctions = @[linearTiming, easeOutTiming, linearTiming, linearTiming, linearTiming, linearTiming, linearTiming];
	factGrid04SmOpacityAnimation.beginTime = beginTime;
	factGrid04SmOpacityAnimation.fillMode = fillMode;
	factGrid04SmOpacityAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"fact-grid-04-sm"] layer] addAnimation:factGrid04SmOpacityAnimation forKey:@"Fade In Blocks_Opacity"];

	CAKeyframeAnimation *factGrid09SmOpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
	factGrid09SmOpacityAnimation.duration = 6.500;
	factGrid09SmOpacityAnimation.values = @[@(0.000), @(1.000), @(1.000), @(0.000), @(0.000), @(0.000), @(1.000), @(1.000)];
	factGrid09SmOpacityAnimation.keyTimes = @[@(0.000), @(0.015), @(0.308), @(0.323), @(0.923), @(0.962), @(0.969), @(1.000)];
	factGrid09SmOpacityAnimation.timingFunctions = @[easeOutTiming, linearTiming, linearTiming, linearTiming, linearTiming, linearTiming, linearTiming];
	factGrid09SmOpacityAnimation.beginTime = beginTime;
	factGrid09SmOpacityAnimation.fillMode = fillMode;
	factGrid09SmOpacityAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"fact-grid-09-sm"] layer] addAnimation:factGrid09SmOpacityAnimation forKey:@"Fade In Blocks_Opacity"];

	CAKeyframeAnimation *grfxIconGridOpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
	grfxIconGridOpacityAnimation.duration = 6.500;
	grfxIconGridOpacityAnimation.values = @[@(0.000), @(0.000), @(1.000), @(1.000), @(1.000), @(0.000), @(0.000)];
	grfxIconGridOpacityAnimation.keyTimes = @[@(0.000), @(0.354), @(0.385), @(0.923), @(0.938), @(0.954), @(1.000)];
	grfxIconGridOpacityAnimation.timingFunctions = @[linearTiming, linearTiming, linearTiming, linearTiming, linearTiming, linearTiming];
	grfxIconGridOpacityAnimation.beginTime = beginTime;
	grfxIconGridOpacityAnimation.fillMode = fillMode;
	grfxIconGridOpacityAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"grfx-icon-grid"] layer] addAnimation:grfxIconGridOpacityAnimation forKey:@"Fade In Blocks_Opacity"];

	CAKeyframeAnimation *grfxIconGridTranslationXAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.translation.x"];
	grfxIconGridTranslationXAnimation.duration = 6.500;
	grfxIconGridTranslationXAnimation.values = @[@(0.000), @(0.000), @(250.000), @(250.000), @(-5.000), @(-5.000)];
	grfxIconGridTranslationXAnimation.keyTimes = @[@(0.000), @(0.638), @(0.692), @(0.923), @(0.938), @(1.000)];
	grfxIconGridTranslationXAnimation.timingFunctions = @[linearTiming, linearTiming, linearTiming, linearTiming, linearTiming];
	grfxIconGridTranslationXAnimation.beginTime = beginTime;
	grfxIconGridTranslationXAnimation.fillMode = fillMode;
	grfxIconGridTranslationXAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"grfx-icon-grid"] layer] addAnimation:grfxIconGridTranslationXAnimation forKey:@"Fade In Blocks_TranslationX"];

	CAKeyframeAnimation *grfxIconGridTranslationYAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.translation.y"];
	grfxIconGridTranslationYAnimation.duration = 6.500;
	grfxIconGridTranslationYAnimation.values = @[@(0.000), @(0.000), @(0.000)];
	grfxIconGridTranslationYAnimation.keyTimes = @[@(0.000), @(0.638), @(1.000)];
	grfxIconGridTranslationYAnimation.timingFunctions = @[linearTiming, linearTiming];
	grfxIconGridTranslationYAnimation.beginTime = beginTime;
	grfxIconGridTranslationYAnimation.fillMode = fillMode;
	grfxIconGridTranslationYAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"grfx-icon-grid"] layer] addAnimation:grfxIconGridTranslationYAnimation forKey:@"Fade In Blocks_TranslationY"];

	CAKeyframeAnimation *factGrid07SmOpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
	factGrid07SmOpacityAnimation.duration = 6.500;
	factGrid07SmOpacityAnimation.values = @[@(0.000), @(0.000), @(1.000), @(1.000), @(0.000), @(0.000), @(0.000), @(1.000), @(1.000)];
	factGrid07SmOpacityAnimation.keyTimes = @[@(0.000), @(0.031), @(0.046), @(0.308), @(0.323), @(0.923), @(0.977), @(0.992), @(1.000)];
	factGrid07SmOpacityAnimation.timingFunctions = @[linearTiming, easeOutTiming, linearTiming, linearTiming, linearTiming, linearTiming, linearTiming, linearTiming];
	factGrid07SmOpacityAnimation.beginTime = beginTime;
	factGrid07SmOpacityAnimation.fillMode = fillMode;
	factGrid07SmOpacityAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"fact-grid-07-sm"] layer] addAnimation:factGrid07SmOpacityAnimation forKey:@"Fade In Blocks_Opacity"];

	CAKeyframeAnimation *factGrid01SmOpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
	factGrid01SmOpacityAnimation.duration = 6.500;
	factGrid01SmOpacityAnimation.values = @[@(0.000), @(0.000), @(1.000), @(1.000), @(1.000), @(1.000), @(1.000)];
	factGrid01SmOpacityAnimation.keyTimes = @[@(0.000), @(0.062), @(0.077), @(0.308), @(0.962), @(0.992), @(1.000)];
	factGrid01SmOpacityAnimation.timingFunctions = @[linearTiming, easeOutTiming, linearTiming, linearTiming, linearTiming, linearTiming];
	factGrid01SmOpacityAnimation.beginTime = beginTime;
	factGrid01SmOpacityAnimation.fillMode = fillMode;
	factGrid01SmOpacityAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"fact-grid-01-sm"] layer] addAnimation:factGrid01SmOpacityAnimation forKey:@"Fade In Blocks_Opacity"];

	CAKeyframeAnimation *factGrid01SmScaleXAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.scale.x"];
	factGrid01SmScaleXAnimation.duration = 6.500;
	factGrid01SmScaleXAnimation.values = @[@(1.000), @(1.000), @(3.047), @(3.047), @(3.047), @(1.000), @(1.000)];
	factGrid01SmScaleXAnimation.keyTimes = @[@(0.000), @(0.308), @(0.346), @(0.923), @(0.962), @(0.969), @(1.000)];
	factGrid01SmScaleXAnimation.timingFunctions = @[linearTiming, linearTiming, linearTiming, linearTiming, linearTiming, linearTiming];
	factGrid01SmScaleXAnimation.beginTime = beginTime;
	factGrid01SmScaleXAnimation.fillMode = fillMode;
	factGrid01SmScaleXAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"fact-grid-01-sm"] layer] addAnimation:factGrid01SmScaleXAnimation forKey:@"Fade In Blocks_ScaleX"];

	CAKeyframeAnimation *factGrid01SmScaleYAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.scale.y"];
	factGrid01SmScaleYAnimation.duration = 6.500;
	factGrid01SmScaleYAnimation.values = @[@(1.000), @(1.000), @(3.047), @(3.047), @(3.047), @(1.000), @(1.000)];
	factGrid01SmScaleYAnimation.keyTimes = @[@(0.000), @(0.308), @(0.346), @(0.923), @(0.962), @(0.969), @(1.000)];
	factGrid01SmScaleYAnimation.timingFunctions = @[linearTiming, linearTiming, linearTiming, linearTiming, linearTiming, linearTiming];
	factGrid01SmScaleYAnimation.beginTime = beginTime;
	factGrid01SmScaleYAnimation.fillMode = fillMode;
	factGrid01SmScaleYAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"fact-grid-01-sm"] layer] addAnimation:factGrid01SmScaleYAnimation forKey:@"Fade In Blocks_ScaleY"];

	CAKeyframeAnimation *factGrid01SmTranslationXAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.translation.x"];
	factGrid01SmTranslationXAnimation.duration = 6.500;
	factGrid01SmTranslationXAnimation.values = @[@(0.000), @(0.000), @(119.748), @(119.748), @(119.748), @(1.021), @(1.021)];
	factGrid01SmTranslationXAnimation.keyTimes = @[@(0.000), @(0.308), @(0.346), @(0.923), @(0.962), @(0.969), @(1.000)];
	factGrid01SmTranslationXAnimation.timingFunctions = @[linearTiming, linearTiming, linearTiming, linearTiming, linearTiming, linearTiming];
	factGrid01SmTranslationXAnimation.beginTime = beginTime;
	factGrid01SmTranslationXAnimation.fillMode = fillMode;
	factGrid01SmTranslationXAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"fact-grid-01-sm"] layer] addAnimation:factGrid01SmTranslationXAnimation forKey:@"Fade In Blocks_TranslationX"];

	CAKeyframeAnimation *factGrid01SmTranslationYAnimation = [CAKeyframeAnimation animationWithKeyPath:@"transform.translation.y"];
	factGrid01SmTranslationYAnimation.duration = 6.500;
	factGrid01SmTranslationYAnimation.values = @[@(0.000), @(0.000), @(119.748), @(119.748), @(119.748), @(1.021), @(1.021)];
	factGrid01SmTranslationYAnimation.keyTimes = @[@(0.000), @(0.308), @(0.346), @(0.923), @(0.962), @(0.969), @(1.000)];
	factGrid01SmTranslationYAnimation.timingFunctions = @[linearTiming, linearTiming, linearTiming, linearTiming, linearTiming, linearTiming];
	factGrid01SmTranslationYAnimation.beginTime = beginTime;
	factGrid01SmTranslationYAnimation.fillMode = fillMode;
	factGrid01SmTranslationYAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"fact-grid-01-sm"] layer] addAnimation:factGrid01SmTranslationYAnimation forKey:@"Fade In Blocks_TranslationY"];

	CAKeyframeAnimation *factGrid01LgOpacityAnimation = [CAKeyframeAnimation animationWithKeyPath:@"opacity"];
	factGrid01LgOpacityAnimation.duration = 6.500;
	factGrid01LgOpacityAnimation.values = @[@(0.000), @(0.000), @(1.000), @(1.000), @(1.000), @(0.000), @(0.000)];
	factGrid01LgOpacityAnimation.keyTimes = @[@(0.000), @(0.346), @(0.354), @(0.923), @(0.946), @(0.954), @(1.000)];
	factGrid01LgOpacityAnimation.timingFunctions = @[linearTiming, linearTiming, linearTiming, linearTiming, linearTiming, linearTiming];
	factGrid01LgOpacityAnimation.beginTime = beginTime;
	factGrid01LgOpacityAnimation.fillMode = fillMode;
	factGrid01LgOpacityAnimation.removedOnCompletion = removedOnCompletion;
	[[self.viewsByName[@"fact-grid-01-lg"] layer] addAnimation:factGrid01LgOpacityAnimation forKey:@"Fade In Blocks_Opacity"];
}

- (void)removeFadeInBlocksAnimation
{
	[self.layer removeAnimationForKey:@"FadeInBlocks"];
	[[self.viewsByName[@"grfx-arrow-right"] layer] removeAnimationForKey:@"Fade In Blocks_Opacity"];
	[[self.viewsByName[@"grfx-arrow-right"] layer] removeAnimationForKey:@"Fade In Blocks_TranslationX"];
	[[self.viewsByName[@"fact-grid-06-sm"] layer] removeAnimationForKey:@"Fade In Blocks_Opacity"];
	[[self.viewsByName[@"fact-grid-02-sm"] layer] removeAnimationForKey:@"Fade In Blocks_Opacity"];
	[[self.viewsByName[@"fact-grid-03-sm"] layer] removeAnimationForKey:@"Fade In Blocks_Opacity"];
	[[self.viewsByName[@"fact-copy-01"] layer] removeAnimationForKey:@"Fade In Blocks_Opacity"];
	[[self.viewsByName[@"fact-copy-01"] layer] removeAnimationForKey:@"Fade In Blocks_TranslationX"];
	[[self.viewsByName[@"fact-grid-08-sm"] layer] removeAnimationForKey:@"Fade In Blocks_Opacity"];
	[[self.viewsByName[@"grfx-fact-bg"] layer] removeAnimationForKey:@"Fade In Blocks_Opacity"];
	[[self.viewsByName[@"grfx-fact-bg"] layer] removeAnimationForKey:@"Fade In Blocks_TranslationX"];
	[[self.viewsByName[@"fact-grid-05-sm"] layer] removeAnimationForKey:@"Fade In Blocks_Opacity"];
	[[self.viewsByName[@"fact-grid-04-sm"] layer] removeAnimationForKey:@"Fade In Blocks_Opacity"];
	[[self.viewsByName[@"fact-grid-09-sm"] layer] removeAnimationForKey:@"Fade In Blocks_Opacity"];
	[[self.viewsByName[@"grfx-icon-grid"] layer] removeAnimationForKey:@"Fade In Blocks_Opacity"];
	[[self.viewsByName[@"grfx-icon-grid"] layer] removeAnimationForKey:@"Fade In Blocks_TranslationX"];
	[[self.viewsByName[@"grfx-icon-grid"] layer] removeAnimationForKey:@"Fade In Blocks_TranslationY"];
	[[self.viewsByName[@"fact-grid-07-sm"] layer] removeAnimationForKey:@"Fade In Blocks_Opacity"];
	[[self.viewsByName[@"fact-grid-01-sm"] layer] removeAnimationForKey:@"Fade In Blocks_Opacity"];
	[[self.viewsByName[@"fact-grid-01-sm"] layer] removeAnimationForKey:@"Fade In Blocks_ScaleX"];
	[[self.viewsByName[@"fact-grid-01-sm"] layer] removeAnimationForKey:@"Fade In Blocks_ScaleY"];
	[[self.viewsByName[@"fact-grid-01-sm"] layer] removeAnimationForKey:@"Fade In Blocks_TranslationX"];
	[[self.viewsByName[@"fact-grid-01-sm"] layer] removeAnimationForKey:@"Fade In Blocks_TranslationY"];
	[[self.viewsByName[@"fact-grid-01-lg"] layer] removeAnimationForKey:@"Fade In Blocks_Opacity"];
}

- (void)animationDidStop:(CAAnimation *)anim finished:(BOOL)flag
{
	void (^completion)(BOOL) = [self.completionBlocksByAnimation objectForKey:anim];
	[self.completionBlocksByAnimation removeObjectForKey:anim];
	if (completion)
	{
		completion(flag);
	}
}

- (void)removeAllAnimations
{
	for (UIView *view in self.viewsByName.allValues)
	{
		[view.layer removeAllAnimations];
	}
	[self.layer removeAnimationForKey:@"FadeInBlocks"];
}

@end