//
// IPadFactsView.h
// Generated by Core Animator version 1.1.1 on 7/15/15.
//
// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED AND WILL BE OVERWRITTEN
//

#import <UIKit/UIKit.h>

IB_DESIGNABLE
@interface IPadFactsView : UIView

@property (strong, nonatomic) NSDictionary *viewsByName;

// Fade In Blocks
- (void)addFadeInBlocksAnimation;
- (void)addFadeInBlocksAnimationWithCompletion:(void (^)(BOOL finished))completionBlock;
- (void)addFadeInBlocksAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion;
- (void)addFadeInBlocksAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)addFadeInBlocksAnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode andRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)removeFadeInBlocksAnimation;

- (void)removeAllAnimations;

- (void)loadInAnimation;

@end